deploymentMode: "SelectorSyncSet"
selectorSyncSet:
    matchLabels:
      hive.openshift.io/cluster-platform: aws
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values:
      - "true"
    - key: ext-managed.openshift.io/legacy-ingress-support
      operator: NotIn
      values: ["false"]
    - key: hive.openshift.io/version-major-minor
      operator: NotIn
      values: ["4.5", "4.6", "4.7", "4.8", "4.9", "4.10", "4.11", "4.12"]
    resourceApplyMode: Upsert
