---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osd-legacy-ingress-feature-labeller
rules:
- apiGroups:
  - "hive.openshift.io/v1"
  resources:
  - clusterdeployments
  verbs:
  - "list"
  - "get"
  - "update"
